package com.myspace.pqr_sac;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class requestClient implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Area")
	private java.lang.String area;
	@org.kie.api.definition.type.Label("Cliente")
	private java.lang.String client;
	@org.kie.api.definition.type.Label("Fecha de la Solicitud")
	private java.util.Date dateRequest;
	@org.kie.api.definition.type.Label("Direccion de correo")
	private java.lang.String emailRequest;
	@org.kie.api.definition.type.Label("Cliente")
	private java.lang.String idClient;
	@org.kie.api.definition.type.Label("Solicitud")
	private java.lang.String request;
	@org.kie.api.definition.type.Label("Tipo de solicitud")
	private java.lang.String requestType;

	public requestClient() {
	}

	public java.lang.String getArea() {
		return this.area;
	}

	public void setArea(java.lang.String area) {
		this.area = area;
	}

	public java.lang.String getClient() {
		return this.client;
	}

	public void setClient(java.lang.String client) {
		this.client = client;
	}

	public java.util.Date getDateRequest() {
		return this.dateRequest;
	}

	public void setDateRequest(java.util.Date dateRequest) {
		this.dateRequest = dateRequest;
	}

	public java.lang.String getEmailRequest() {
		return this.emailRequest;
	}

	public void setEmailRequest(java.lang.String emailRequest) {
		this.emailRequest = emailRequest;
	}

	public java.lang.String getIdClient() {
		return this.idClient;
	}

	public void setIdClient(java.lang.String idClient) {
		this.idClient = idClient;
	}

	public java.lang.String getRequest() {
		return this.request;
	}

	public void setRequest(java.lang.String request) {
		this.request = request;
	}

	public java.lang.String getRequestType() {
		return this.requestType;
	}

	public void setRequestType(java.lang.String requestType) {
		this.requestType = requestType;
	}

	public requestClient(java.lang.String area, java.lang.String client,
			java.util.Date dateRequest, java.lang.String emailRequest,
			java.lang.String idClient, java.lang.String request,
			java.lang.String requestType) {
		this.area = area;
		this.client = client;
		this.dateRequest = dateRequest;
		this.emailRequest = emailRequest;
		this.idClient = idClient;
		this.request = request;
		this.requestType = requestType;
	}

}